version: 2
jobs:
  build:
    context: NPM
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |     
            sudo npm install -g npm-cli-login publish
            yarn  
            yarn build
            npm run login
            npm run 2npm